// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlfgJqAxShJUXZdSlF24Fbw2sEioSbMA',
    appId: '1:60545849443:web:1e9e17494b4c2abf594056',
    messagingSenderId: '60545849443',
    projectId: 'fir-test-129',
    authDomain: 'fir-test-129.firebaseapp.com',
    storageBucket: 'fir-test-129.appspot.com',
    measurementId: 'G-WBQSB12SSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZSet4ANOfpqlZzKamamDAryWS-t80SzQ',
    appId: '1:60545849443:android:90fe24c347353518594056',
    messagingSenderId: '60545849443',
    projectId: 'fir-test-129',
    storageBucket: 'fir-test-129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvuGFeKRscFzkLXB_koqTxf-4DxaDVhNg',
    appId: '1:60545849443:ios:f766da8790bb3a9e594056',
    messagingSenderId: '60545849443',
    projectId: 'fir-test-129',
    storageBucket: 'fir-test-129.appspot.com',
    iosClientId: '60545849443-7n2e586oisie5jn0rg66jjqto6iah3td.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest129',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvuGFeKRscFzkLXB_koqTxf-4DxaDVhNg',
    appId: '1:60545849443:ios:f766da8790bb3a9e594056',
    messagingSenderId: '60545849443',
    projectId: 'fir-test-129',
    storageBucket: 'fir-test-129.appspot.com',
    iosClientId: '60545849443-7n2e586oisie5jn0rg66jjqto6iah3td.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest129',
  );
}
